### ISSUE TITLE
Decide which branch to use

### ISSUE THREAD

**Issue by andrewda** [SouthEugeneRoboticsTeam/ursa#12]
Currently there seem to be lots of commits to both `master` and `dev` (which currently means quite a few nasty merge conflicts). Instead of using two branches like this, we should instead have one primary branch (either `master` or `dev`) and commit directly to it or, preferably, use feature branches for everything else and make Pull Requests.

**Comment by joshua255** [comment]
I've been leaving everything in dev because Connor pushed some code into
master and I don't know yet if we'll need to use it. Is there any reason to
create a task to run a loop code instead of using void loop which is
basically the same thing?) I'll move it it of master.
