### ISSUE TITLE
disable if no wifi signal after time

### ISSUE THREAD

**Issue by joshua255** [SouthEugeneRoboticsTeam/ursa#26]

**Comment by andrewda** [comment]
I think this is the same as disabling if no packets are received after X milliseconds.

**Comment by joshua255** [comment]
yeah, I'd just add a variable to record the millis() at each time a packet is received then keep an eye on it. I think I know how to make this change, I made the issue so I wouldn't forget. 

The parts came, and your parents got one of the two esp32s to me to test with-I'm trying to send it UDP packets now. Let me know if there is anything you'd like me to test.
