### ISSUE TITLE
Hard code address

### ISSUE THREAD

**Issue by andrewda** [SouthEugeneRoboticsTeam/ursa#27]
It seems as though the default address is `192.168.4.1` but it'd be good to hard code that in. If we do get this working, it might be nice to set the address to `10.25.21.1` for no reason other than that's what the FRC robots use.

**Comment by joshua255** [comment]
`  WiFi.softAPConfig(IPAddress(10, 25, 21, ROBOT_ID), IPAddress(10, 25, 21, ROBOT_ID), IPAddress(255, 255, 255, 0));`
seems to work! This change will be in my wifi-testing pull request after I check some more things.

**Comment by joshua255** [comment]
Would you prefer the robot_id as the last number so each robot is identifiable if they were all connected together (but then softAPConfig wouldn't be used anyways) or do you want a 1 on the end as you said?

**Comment by ghost** [comment]
I think it should be constant because the driver station would need to know the last digit if it changed on each robot, and that would add an unnecessary step to setting them up.

**Comment by andrewda** [comment]
I agree with @circuitbird, though it might be nice to have a nice flag at the top of the file which can configure to make it the robot id instead.

**Comment by joshua255** [comment]
What purpose would a flag to just change the IP address serve? An interesting enhancement to consider would be putting a flag in the code to make the robot switch to connecting to a wifi network instead of creating one.

**Comment by ghost** [comment]
Perhaps changing ip/connecting to a network should be features for another branch, since so many changes to the code would be required. It's totally possible to put both modes is the same file and have some kind of selector, but I think the resulting clutter would not be worth it.

**Comment by andrewda** [comment]
Yeah either of those would work. A physical switch on the robot would be cool too.

**Comment by andrewda** [comment]
Just for reference:

https://github.com/espressif/arduino-esp32/issues/985#issuecomment-359157428

**Comment by joshua255** [comment]
the hardcoded address has been very reliable. The reference above suggested a delay, so I put the gyro zeroing code before setting the access point, because it causes a short delay.
