### ISSUE TITLE
Save and recall pid settings

### ISSUE THREAD

**Issue by joshua255** [SouthEugeneRoboticsTeam/ursa#39]

**Comment by joshua255** [comment]
@andrewda any ideas for how the robot can know when to save its values?

**Comment by joshua255** [comment]
Here's my ideas for what to do:

- [x] make functions to save variables to memory that lasts between power cycles

- [x] on startup, recall saved variables

- [x] send saved settings to DS until acknowledged (while a byte at the end of the message==1)

- [x] save settings, when told to by the DS (a byte at the end of the message==2)

**Comment by ghost** [comment]
@joshua255 the [ESP32 EEPROM library](https://github.com/espressif/arduino-esp32/blob/master/libraries/EEPROM/src/EEPROM.cpp) already has functions for reading/writing all primitive data types. Also, some of the write functions were still writing to the wifi send buffer. I've switched the code to use the API functions in 918057ca266ca13b3cca50a7b7ebe225a72397e2.

**Comment by joshua255** [comment]
Thanks @circuitbird! Writing to wifi explains why everything was broken for me. The write float functions look very nice.
