### ISSUE TITLE
blink builtin status led like FRC RSLs, not on when enabled and off when disabled

### ISSUE THREAD

**Issue by joshua255** [SouthEugeneRoboticsTeam/ursa#45]
Where the led is currently set HIGH, make it blink, and where it is currently set LOW, set it HIGH

try: digitalWrite(LED_BUILTIN,(millis()%blinkPeriod<timeOn)); for making a light blink on and off every blinkPeriod milliseconds staying on for timeOn milliseconds of that. (replace blinkPeriod with approximately 1000 and timeOn with about 500)

**Comment by SamBosch77** [comment]
Are there different colored LEDs that we want to activate or is this only a "blinking when enabled" kind of status LED?
